
-- Thaise
--Atualizar comentários das tabelas do schema contratos
comment on table contratos.aio is 'Tabela com informacoes da emissao de Autorizacao de Inicio de Obra';
comment on table contratos.aio_log_rec is 'Tabela de auditoria'; 
comment on table contratos.anexo is 'Tabela com dados de registros de anexo: contrato e termo aditivo do contrato';
comment on table contratos.anexo_log_rec is 'Tabela de auditoria';
comment on table contratos.contrato is 'Tabela dos contratos de dado Instrumento que passou pela VRPL';
comment on table contratos.contrato_log_rec is 'Tabela de auditoria';
comment on table contratos.doc_complementar is 'Tabela para conter a documentação complementar inserida na fase de Contratos';
comment on table contratos.doc_complementar_log_rec is 'Tabela de auditoria';
comment on table contratos.fornecedor is 'Tabela com o fornecedor de dados contrato';
comment on table contratos.fornecedor_log_rec is 'Tabela de auditoria';
comment on table contratos.historico is 'Tabela com o histórico de eventos dos contratos e seus respectivos termos aditivos';
comment on table contratos.historico_log_rec is 'Tabela de auditoria';
comment on table contratos.licitacao is 'Tabela com a licitação de dados contrato';
comment on table contratos.licitacao_log_rec is 'Tabela de auditoria';
comment on table contratos.lote is 'Tabela com a composição dos lotes de um contrato, provenientes da VRPL';
comment on table contratos.lote_log_rec is 'Tabela de auditoria';
comment on table contratos.meta is 'Tabela com a composição dos lotes de um contrato, provenientes da VRPL/Projeto básico';
comment on table contratos.meta_log_rec is 'Tabela de auditoria';
comment on table contratos.po is 'Tabela com a composição das PO das submetas de um contrato provenientes da VRPL';
comment on table contratos.po_log_rec is 'Tabela de auditoria';
comment on table contratos.proposta is 'Tabela com informações do Projeto Básico do núcleo do sistema';
comment on table contratos.proposta_log_rec is 'Tabela de auditoria';
comment on table contratos.submeta is 'Tabela com a composição das submetas dos Lotes de um contrato provenientes da VRPL';
comment on table contratos.submeta_log_rec is 'Tabela de auditoria';
comment on table contratos.submeta_doc_complementar is 'Tabela com indicação a que submeta a documentação complementar faz referência';
comment on table contratos.submeta_doc_complementar_log_rec is 'Tabela de auditoria';
comment on table contratos.termo_aditivo is 'Tabela dos termos aditivos de dados contrato';
comment on table contratos.termo_aditivo_log_rec is 'Tabela de auditoria';

comment on table contratos.execucao_batch_aio is 'Relatorio de execucao do servico batch de emissao de AIO';
comment on table contratos.databasechangelog is 'Log de mudancas para o liquibase';
comment on table contratos.databasechangeloglock is '';


--Atualizar comentários das colunas das tabelas do schema contratos

--aio
comment on column contratos.aio.id is 'Chave identificadora da tabela de Autorizacao de inicio de Obra';
comment on column contratos.aio.proposta_fk is 'Referencia o identificador de contratos.proposta';
comment on column contratos.aio.contrato_emissor_fk  is 'Referencia o identificador do contrato responsavel pela emissao do AIO';
comment on column contratos.aio.dt_emissao_aio is 'Data de emissao do AIO';
comment on column contratos.aio.emissor is 'Agente que realizou a emissãodo AIO';
comment on column contratos.aio.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.aio.adt_login is 'CPF do usuario que realizou a operacao ';
comment on column contratos.aio.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.aio.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
--aio_log_rec
comment on column contratos.aio_log_rec.entity_id is 'Referencia a tabela de AIO que deu origem a operacao';
comment on column contratos.aio_log_rec.id is 'Chave identificadora da tabela de auditoria de AIO';
comment on column contratos.aio_log_rec.proposta_fk is 'Referencia o identificador de contratos.proposta';
comment on column contratos.aio_log_rec.contrato_emissor_fk  is 'Referencia o identificador do contrato responsavel pela emissao do AIO';
comment on column contratos.aio_log_rec.dt_emissao_aio is 'Data de emissao do AIO';
comment on column contratos.aio_log_rec.emissor is 'Agente que realizou a emissãodo AIO';
comment on column contratos.aio_log_rec.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.aio_log_rec.adt_login is 'CPF do usuario que realizou a operacao ';
comment on column contratos.aio_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.aio_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';

-- anexos
comment on column contratos.anexo.id is 'Chave identificadora do anexo';
comment on column contratos.anexo.tx_descricao is 'Descricao do anexo';
comment on column contratos.anexo.in_tipo_anexo is 'Tipo de anexo: INSTRUMENTO_CONTRATUAL, PUBLICACAO_TERMO_ADITIVO, PUBLICACAO_EXTRATO, OUTROS, TERMO_ADITIVO';
comment on column contratos.anexo.dt_upload is 'Data de envio do anexo';
comment on column contratos.anexo.id_cpf_enviado_por  is 'CPF do usuario que realizou a operacao';
comment on column contratos.anexo.nome_enviado_por is 'Nome do usuario que realizou a operacao';
comment on column contratos.anexo.in_perfil_usuario is 'Perfil CPF do usuario que realizou a operacao: PROPONENTE, MANDATARIA, CONCEDENTE ';
comment on column contratos.anexo.nm_arquivo is 'Nome do arquivo enviado';
comment on column contratos.anexo.caminho is 'Localizacao do arquivo ';
comment on column contratos.anexo.bucket is 'Indicador do repositorio dos arquivos';
comment on column contratos.anexo.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.anexo.adt_login is 'CPF do usuario que realizou a operacao';
comment on column contratos.anexo.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.anexo.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
comment on column contratos.anexo.contrato_id is 'Referencia ao Identificador do contrato para anexos de contrato';
comment on column contratos.anexo.termo_aditivo_id is 'Referencia ao Identificador do Termo Aditivo para anexos do TA do contrato';
-- anexos_log_rec
comment on column contratos.anexo_log_rec.id is 'Chave identificadora do anexo_log_rec';
comment on column contratos.anexo_log_rec.entity_id is 'Referencia a chave identificadora ';
comment on column contratos.anexo_log_rec.tx_descricao is 'Descricao do anexo';
comment on column contratos.anexo_log_rec.in_tipo_anexo is 'Tipo de anexo: INSTRUMENTO_CONTRATUAL, PUBLICACAO_TERMO_ADITIVO, PUBLICACAO_EXTRATO, OUTROS, TERMO_ADITIVO';
comment on column contratos.anexo_log_rec.dt_upload is 'Data de envio do anexo';
comment on column contratos.anexo_log_rec.id_cpf_enviado_por  is 'CPF do usuario que realizou a operacao';
comment on column contratos.anexo_log_rec.nome_enviado_por is 'Nome do usuario que realizou a operacao';
comment on column contratos.anexo_log_rec.in_perfil_usuario is 'Perfil CPF do usuario que realizou a operacao: PROPONENTE, MANDATARIA, CONCEDENTE ';
comment on column contratos.anexo_log_rec.nm_arquivo is 'Nome do arquivo enviado';
comment on column contratos.anexo_log_rec.caminho is 'Localizacao do arquivo ';
comment on column contratos.anexo_log_rec.bucket is 'Indicador do repositorio dos arquivos';
comment on column contratos.anexo_log_rec.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.anexo_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
comment on column contratos.anexo_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.anexo_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
comment on column contratos.anexo_log_rec.contratoid is 'Referencia ao Identificador do contrato para anexos de contrato';
comment on column contratos.anexo_log_rec.termoaditivoid is 'Referencia ao Identificador do Termo Aditivo para anexos do TA do contrato';
--contrato
 comment on column contratos.contrato.id is 'Identificador da tabela de contratos';  
comment on column contratos.contrato.numero  is 'Numero atribuido ao contrato';
comment on column contratos.contrato.objeto  is 'Descrição de objeto do contrato';
comment on column contratos.contrato.data_assinatura  is 'Data da assinatura';
comment on column contratos.contrato.data_publicacao  is 'Data  de publicacao';
comment on column contratos.contrato.inicio_vigencia  is 'Data de inicio de vigencia';
comment on column contratos.contrato.fim_vigencia  is 'Data de termino de vigencia atual do contrato';
comment on column contratos.contrato.valor_total  is 'Valor total informado para o contrato';
comment on column contratos.contrato.in_situacao  is 'Situacao do contrato: em rascunho, concluido, excluido';
comment on column contratos.contrato.versao  is 'Versao usada para controlar a concorrencia';
comment on column contratos.contrato.adt_login  is 'CPF do usuario que realizou a operacao';
comment on column contratos.contrato.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.contrato.adt_operacao  is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
comment on column contratos.contrato.proposta_id  is 'Identificado da proposta no contrato ';
comment on column contratos.contrato.dt_fim_vigencia_original  is 'Data fim de vigencia registrada originalmente para o contrato';
--contratos_log_rec
comment on column contratos.contrato_log_rec.id is 'Identificador da tabela de contrato_log_rec';  
comment on column contratos.contrato_log_rec.entity_id is 'Referencia ao registro original de contratos ';  
comment on column contratos.contrato_log_rec.numero  is 'Numero atribuido ao contrato';
comment on column contratos.contrato_log_rec.objeto  is 'Descrição de objeto do contrato';
comment on column contratos.contrato_log_rec.data_assinatura  is 'Data da assinatura';
comment on column contratos.contrato_log_rec.data_publicacao  is 'Data  de publicacao';
comment on column contratos.contrato_log_rec.inicio_vigencia  is 'Data de inicio de vigencia';
comment on column contratos.contrato_log_rec.fim_vigencia  is 'Data de termino de vigencia atual do contrato';
comment on column contratos.contrato_log_rec.valor_total  is 'Valor total informado para o contrato';
comment on column contratos.contrato_log_rec.in_situacao  is 'Situacao do contrato: em rascunho, concluido, excluido';
comment on column contratos.contrato_log_rec.versao  is 'Versao usada para controlar a concorrencia';
comment on column contratos.contrato_log_rec.adt_login  is 'CPF do usuario que realizou a operacao';
comment on column contratos.contrato_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.contrato_log_rec.adt_operacao  is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
comment on column contratos.contrato_log_rec.propostaid  is 'Identificado da proposta no contrato ';
comment on column contratos.contrato_log_rec.dt_fim_vigencia_original  is 'Data fim de vigencia registrada originalmente para o contrato';

--doc_complementar
comment on column contratos.doc_complementar.id is 'Identificador da tabela de Doc_complementar '; 
comment on column contratos.doc_complementar.numero_documento is 'Numero do documento'; 
comment on column contratos.doc_complementar.orgao_emissor is 'Orgao responsavel pela emissao do documento'; 
comment on column contratos.doc_complementar.data_emissao is 'Data de emissao do documento'; 
comment on column contratos.doc_complementar.data_validade is 'Data de validade do documento'; 
comment on column contratos.doc_complementar.tipo is 'Tipo do documento'; 
comment on column contratos.doc_complementar.tipo_manifesto_ambiental is 'Tipo quando for manifesto ambiental'; 
comment on column contratos.doc_complementar.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.doc_complementar.adt_login is 'CPF do usuario que realizou a operacao';
comment on column contratos.doc_complementar.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.doc_complementar.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
comment on column contratos.doc_complementar.anexo_id is 'Referencia ao anexo que representa o documento';
--doc_complementar_log_rec
comment on column contratos.doc_complementar_log_rec.id is 'Identificador da tabela de Doc_complementar '; 
comment on column contratos.doc_complementar_log_rec.entity_id is 'Identificador da tabela de Doc_complementar '; 
comment on column contratos.doc_complementar_log_rec.numero_documento is 'Numero do documento'; 
comment on column contratos.doc_complementar_log_rec.orgao_emissor is 'Orgao responsavel pela emissao do documento'; 
comment on column contratos.doc_complementar_log_rec.data_emissao is 'Data de emissao do documento'; 
comment on column contratos.doc_complementar_log_rec.data_validade is 'Data de validade do documento'; 
comment on column contratos.doc_complementar_log_rec.tipo is 'Tipo do documento'; 
comment on column contratos.doc_complementar_log_rec.tipo_manifesto_ambiental is 'Tipo quando for manifesto ambiental'; 
comment on column contratos.doc_complementar_log_rec.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.doc_complementar_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
comment on column contratos.doc_complementar_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.doc_complementar_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
comment on column contratos.doc_complementar_log_rec.anexoid is 'Referencia ao anexo que representa o documento';
--fornecedor
comment on column contratos.fornecedor.id is 'Identificador do fornecedor nos contratos'; 
comment on column contratos.fornecedor.razao_social is 'Nome social do Fornecedor'; 
comment on column contratos.fornecedor.tipo_identificacao is 'Tipo de Identificacao CNPJ, CPF , IG'; 
comment on column contratos.fornecedor.identificacao is 'Numero do identificador CNPJ, CPF , IG'; 
comment on column contratos.fornecedor.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.fornecedor.adt_login is 'CPF do usuario que realizou a operacao';
comment on column contratos.fornecedor.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.fornecedor.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
--fornecedor_log_rec
comment on column contratos.fornecedor_log_rec.id is 'Identificador do fornecedor_log_rec nos contratos'; 
comment on column contratos.fornecedor_log_rec.entity_id is 'Referencia ap identificador do fornecedor nos contratos'; 
comment on column contratos.fornecedor_log_rec.razao_social is 'Nome social do Fornecedor'; 
comment on column contratos.fornecedor_log_rec.tipo_identificacao is 'Tipo de Identificacao CNPJ, CPF , IG'; 
comment on column contratos.fornecedor_log_rec.identificacao is 'Numero do identificador CNPJ, CPF , IG'; 
comment on column contratos.fornecedor_log_rec.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.fornecedor_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
comment on column contratos.fornecedor_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.fornecedor_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
-- historico 
comment on column contratos.historico.id is 'Identificador da tabela de histórico'; 
comment on column contratos.historico.situacao_contrato is 'Situacao do contrato/TA RAS: Em Rascunho, CON: Concluído, EXC: Excluído, RAR: Contrato em Rascunho e Aditivação em Rascunho, RAC: Contrato em Rascunho e Aditivação Concluída, ADR: Contrato Concluído e Aditivação em Rascunho, ADC: Contrato Concluído e Aditivação Concluída';
comment on column contratos.historico.evento_gerador is 'Evento gerador do historico, de acordo com a RN 783370. RAS: Contrato Rascunho, CON: Contrato Concluido, ADR: TA em Rascunho e  Contrato Concluido, ADC: TA Concluido, ADE: TA Excluido, EXC: Contrato excluido, CEA: AIO cancelado, EAC: AIO emitida na conclusao, EAV: AIO emitida na verificacao. '; 
comment on column contratos.historico.nome_responsavel is 'Nome do responsavel pela acao.'; 
comment on column contratos.historico.cpf_responsavel is 'CPF do responsavel pela acao.'; 
comment on column contratos.historico.data_registro is 'Data de rgistro da acao'; 
comment on column contratos.historico.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.historico.adt_login is 'CPF do usuario que realizou a operacao';
comment on column contratos.historico.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.historico.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
comment on column contratos.historico.contrato_id is 'Referencia ao contrato gerador da acao geradora do historico'; 
comment on column contratos.historico.termo_aditivo_id is 'Referencia ao Termo Aditivo gerador da acao geradora do historico'; 
--historico_log_rec
comment on column contratos.historico_log_rec.id is 'Identificador da tabela de historico_log_rec'; 
comment on column contratos.historico_log_rec.entity_id is 'Referencia a entidade Historico geradora do log '; 
comment on column contratos.historico_log_rec.situacao_contrato is 'Situacao do contrato/TA RAS: Em Rascunho, CON: Concluído, EXC: Excluído, RAR: Contrato em Rascunho e Aditivação em Rascunho, RAC: Contrato em Rascunho e Aditivação Concluída, ADR: Contrato Concluído e Aditivação em Rascunho, ADC: Contrato Concluído e Aditivação Concluída';
comment on column contratos.historico_log_rec.evento_gerador is 'Evento gerador do historico, de acordo com a RN 783370. RAS: Contrato Rascunho, CON: Contrato Concluido, ADR: TA em Rascunho e  Contrato Concluido, ADC: TA Concluido, ADE: TA Excluido, EXC: Contrato excluido, CEA: AIO cancelado, EAC: AIO emitida na conclusao, EAV: AIO emitida na verificacao. '; 
comment on column contratos.historico_log_rec.nome_responsavel is 'Nome do responsavel pela acao.'; 
comment on column contratos.historico_log_rec.cpf_responsavel is 'CPF do responsavel pela acao.'; 
comment on column contratos.historico_log_rec.data_registro is 'Data de rgistro da acao'; 
comment on column contratos.historico_log_rec.versao is 'Versao usada para controlar a concorrencia';
comment on column contratos.historico_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
comment on column contratos.historico_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
comment on column contratos.historico_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
comment on column contratos.historico_log_rec.contratoid is 'Referencia ao contrato gerador da acao geradora do historico'; 
comment on column contratos.historico_log_rec.termo_aditivo_id is 'Referencia ao Termo Aditivo gerador da acao geradora do historico'; 

-- Thaise/Fabio

--Licitacao 
comment on column contratos.licitacao.id is 'Identificador da tabela de Licitacao de contratos'; 
comment on column contratos.licitacao.numero_ano is 'Numero/ano proveniente da VRPL'; 
comment on column contratos.licitacao.objeto is 'Objeto da Licitação'; 
comment on column contratos.licitacao.valor_processo is 'Valor em reais do processo licitatório';
comment on column contratos.licitacao.status_processo is 'Status do processo licitatório: Em licitação ou Concluído'; 
comment on column contratos.licitacao.id_licitacao_fk is 'Referencia ao campo id_licitacao_fk  do VRPL_licitacao'; 
comment on column contratos.licitacao.in_situacao is 'Sigla da Situação da documentacao'; 
comment on column contratos.licitacao.modalidade is 'Modalidade, depende do Recurso Nacional ou Internacional:Recurso - Lei 8.666/1993:  Convite, Tomada de Preços, Concorrência e Concurso. Recurso - Lei 10.520/2002 - Pregão: Pregão.'; 
comment on column contratos.licitacao.regime_contratacao is 'Regime Contratacao depende da Origem do Recurso: Recurso Financeiro Nacional: Lei 8.666/1993, Lei 10.520/2002 - Pregão. Recurso Financeiro Internacional: Lei 8.666/1993, Lei 10.520/2002 - Pregão, Shopping, NCB (LPN), ICB (LPI). Demais recursos financeiros: Decreto 93.872/1986, Lei 8.629/1993, Lei 10.847/2004, Lei 11.652/2008, Lei 11.947/2009, Lei 12.462/2011, Lei 12.512/2011, Lei 12.663/2012, Lei 12.865/2013, Lei 12.873/2013 e Lei 13.303/2016'; 
comment on column contratos.licitacao.data_publicacao is 'Data de publicação do Processo de Execução.'; 
comment on column contratos.licitacao.data_homologacao is 'Data de homologação do Processo de Execução.'; 
comment on column contratos.licitacao.processo_de_execucao is 'Define o processo de execução: Licitação, Inexigibilidade, Dispensa, Cotação de Resgistro, Contação de Divulgação e Pesquisa de Mercado.'; 
comment on column contratos.licitacao.versao is 'Versão usada para controlar a concorrência'; 
comment on column contratos.licitacao.adt_login is 'CPF do vrpl_licitacao do usuario logado no momento da clonagem'; 
comment on column contratos.licitacao.adt_data_hora is 'Data/Hora de modificacao do registro'; 
comment on column contratos.licitacao.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro'; 
comment on column contratos.licitacao.proposta_id is 'Referencia a proposta de Contratos'; 
comment on column contratos.licitacao.numero_processo is 'Numero do processo de execucao'; 
comment on column contratos.licitacao.situacao_aceite_processo_execu is 'Situacao do aceite do processo de execucao'; 
comment on column contratos.licitacao.versao_nr is 'Versão do registro da licitacao referente ao controle de versão';
--licitacao_log_rec
comment on column contratos.licitacao_log_rec.id is 'Identificador da tabela de Licitacao_log_rec de contratos'; 
comment on column contratos.licitacao_log_rec.data_publicacao is 'Data de publicação do Processo de Execução.'; 
comment on column contratos.licitacao_log_rec.data_homologacao is 'Data de homologação do Processo de Execução.'; 
comment on column contratos.licitacao_log_rec.entity_id is 'Referencia ao identificador da tabela de Licitacao de contratos'; 
comment on column contratos.licitacao_log_rec.id_licitacao_fk is 'Referencia ao campo id_licitacao_fk  do VRPL_licitacao'; 
comment on column contratos.licitacao_log_rec.in_situacao is 'Sigla da Situação da documentacao'; 
comment on column contratos.licitacao_log_rec.modalidade is 'Modalidade, depende do Recurso Nacional ou Internacional:Recurso - Lei 8.666/1993:  Convite, Tomada de Preços, Concorrência e Concurso. Recurso - Lei 10.520/2002 - Pregão: Pregão.'; 
comment on column contratos.licitacao_log_rec.numero_ano is 'Numero/ano proveniente da VRPL'; 
comment on column contratos.licitacao_log_rec.numero_processo is 'Numero do processo de execucao'; 
comment on column contratos.licitacao_log_rec.objeto is 'Objeto da Licitação'; 
comment on column contratos.licitacao_log_rec.processo_de_execucao is 'Define o processo de execução: Licitação, Inexigibilidade, Dispensa, Cotação de Resgistro, Contação de Divulgação e Pesquisa de Mercado.'; 
comment on column contratos.licitacao_log_rec.propostaid is 'Referencia a proposta de Contratos'; 
comment on column contratos.licitacao_log_rec.regime_contratacao is 'Regime Contratacao depende da Origem do Recurso: Recurso Financeiro Nacional: Lei 8.666/1993, Lei 10.520/2002 - Pregão. Recurso Financeiro Internacional: Lei 8.666/1993, Lei 10.520/2002 - Pregão, Shopping, NCB (LPN), ICB (LPI). Demais recursos financeiros: Decreto 93.872/1986, Lei 8.629/1993, Lei 10.847/2004, Lei 11.652/2008, Lei 11.947/2009, Lei 12.462/2011, Lei 12.512/2011, Lei 12.663/2012, Lei 12.865/2013, Lei 12.873/2013 e Lei 13.303/2016'; 
comment on column contratos.licitacao_log_rec.status_processo is 'Status do processo licitatório: Em licitação ou Concluído'; 
comment on column contratos.licitacao_log_rec.valor_processo is 'Valor em reais do processo licitatório';
comment on column contratos.licitacao_log_rec.versao is 'Versão usada para controlar a concorrência'; 
comment on column contratos.licitacao_log_rec.adt_login is 'CPF do vrpl_licitacao do usuario logado no momento da clonagem'; 
comment on column contratos.licitacao_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro de clonagem'; 
comment on column contratos.licitacao_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro'; 
comment on column contratos.licitacao_log_rec.versao_nr is 'Versão do registro da licitacao referente ao controle de versão';

-- FABIO

 comment on column contratos.lote.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.lote.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.lote.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.lote.contrato_id is 'Id do contrato que o lote esta vinculado';
 comment on column contratos.lote.fornecedor_id is 'Id do fornecedor que o lote esta vinculado';
 comment on column contratos.lote.id is 'Chave primaria do registro da tabela';
 comment on column contratos.lote.licitacao_id is 'Id da licitacao que o lote esta vinculado';
 comment on column contratos.lote.numero is 'Numero do lote';
 comment on column contratos.lote.versao is 'Versao usada para controlar a concorrencia';
 
 comment on column contratos.lote_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.lote_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.lote_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.lote_log_rec.contratoid is 'Id do contrato que o lote esta vinculado';
 comment on column contratos.lote_log_rec.entity_id is 'Id da entidade que esta sendo historiada';
 comment on column contratos.lote_log_rec.fornecedorid is 'Id do fornecedor que o lote esta vinculado';
 comment on column contratos.lote_log_rec.id is 'Chave primaria do registro da tabela';
 comment on column contratos.lote_log_rec.licitacaoid is 'Id da licitacao que o lote esta vinculado';
 comment on column contratos.lote_log_rec.numero is 'Numero do lote';
 comment on column contratos.lote_log_rec.versao is 'Versao usada para controlar a concorrencia';
 
 comment on column contratos.meta.id is 'Chave primaria do registro da tabela';
 comment on column contratos.meta.id_meta_vrpl is 'Id da meta no sistema VRPL';
 comment on column contratos.meta.tx_descricao is 'Descricao da meta';
 comment on column contratos.meta.numero is 'Numero da meta';
 comment on column contratos.meta.qt_itens is 'Quantidade de itens da meta';
 comment on column contratos.meta.in_social is 'Indicador que define se a meta é de projeto social';
 comment on column contratos.meta.versao is 'Versao usada para controlar a concorrencia'; 
 comment on column contratos.meta.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.meta.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.meta.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 
 comment on column contratos.meta_log_rec.id is 'Chave primaria do registro da tabela';
 comment on column contratos.meta_log_rec.entity_id is 'Id da entidade que esta sendo historiada';
 comment on column contratos.meta_log_rec.id_meta_vrpl is 'Id da meta no sistema VRPL';
 comment on column contratos.meta_log_rec.in_social is 'Indicador que define se a meta é de projeto social';
 comment on column contratos.meta_log_rec.numero is 'Numero da meta';
 comment on column contratos.meta_log_rec.qt_itens is 'Quantidade de itens da meta';
 comment on column contratos.meta_log_rec.tx_descricao is 'Descricao da meta';
 comment on column contratos.meta_log_rec.versao is 'Versao usada para controlar a concorrencia';
 comment on column contratos.meta_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.meta_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.meta_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
   
 comment on column contratos.po.id is 'Chave primaria do registro da tabela';
 comment on column contratos.po.id_po_vrpl is 'Identificador da PO no sistema VRPL';
 comment on column contratos.po.submeta_id is 'Chave estrangeira para submeta';
 comment on column contratos.po.dt_previsao_inicio_obra is 'Data de previsao do inicio da obra';
 comment on column contratos.po.qt_meses_duracao_obra is 'Quantidade de meses de duracao da obra';
 comment on column contratos.po.in_acompanhamento_eventos is 'Indica se PO acompanhada por eventos';
 comment on column contratos.po.in_desonerado is 'Indica se PO desonerada';
 comment on column contratos.po.sg_localidade is 'Sigla da localidade';
 comment on column contratos.po.dt_base_analise is 'Data base oriunda da fase de análise';
 comment on column contratos.po.referencia is 'Referência (analise/database) para apresentação dos preços dos serviços';
 comment on column contratos.po.dt_base_vrpl is 'Data base oriunda da fase VRPL';
 comment on column contratos.po.dt_previsao_inicio_obra_analise is 'Data de previsao do inicio da obra da Análise';
 comment on column contratos.po.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.po.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.po.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.po.versao is 'Versao usada para controlar a concorrencia';
 comment on column contratos.po.versao_id is 'Identificador de agrupamento das versões';
 comment on column contratos.po.versao_nm_evento is 'Nome do evento que deu origem à nova versão';
 comment on column contratos.po.versao_nr is 'Identificador do conjunto de dados referente ao versionamento';
 
 comment on column contratos.po_log_rec.id is 'Chave primaria do registro da tabela';
 comment on column contratos.po_log_rec.dt_base_analise is 'Data base oriunda da fase de análise';
 comment on column contratos.po_log_rec.dt_base_vrpl is 'Data base oriunda da fase VRPL';
 comment on column contratos.po_log_rec.dt_previsao_inicio_obra is 'Data de previsao do inicio da obra';
 comment on column contratos.po_log_rec.dt_previsao_inicio_obra_analise is 'Data de previsao do inicio da obra da Análise';
 comment on column contratos.po_log_rec.entity_id is 'Id da entidade que esta sendo historiada';
 comment on column contratos.po_log_rec.id_po_vrpl is 'Identificador da PO no sistema VRPL';
 comment on column contratos.po_log_rec.in_acompanhamento_eventos is 'Indica se PO acompanhada por eventos';
 comment on column contratos.po_log_rec.in_desonerado is 'Indica se PO desonerada';
 comment on column contratos.po_log_rec.qt_meses_duracao_obra is 'Quantidade de meses de duracao da obra';
 comment on column contratos.po_log_rec.referencia is 'Referência (analise/database) para apresentação dos preços dos serviços';
 comment on column contratos.po_log_rec.sg_localidade is 'Sigla da localidade';
 comment on column contratos.po_log_rec.submetaid is 'Id da submeta associada';
 comment on column contratos.po_log_rec.versao is 'Versao usada para controlar a concorrencia';
 comment on column contratos.po_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.po_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.po_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
  
 comment on column contratos.proposta.id is 'Chave primaria do registro da tabela';
 comment on column contratos.proposta.id_siconv is 'Identificador da Proposta no SICONV';
 comment on column contratos.proposta.numero_proposta is 'Número da proposta';
 comment on column contratos.proposta.ano_proposta is 'Ano da proposta';
 comment on column contratos.proposta.valor_global is 'Valor global aceito na análise';
 comment on column contratos.proposta.valor_repasse is 'Valor de repasse aceito na análise';
 comment on column contratos.proposta.valor_contrapartida is 'Valor de contrapartida';
 comment on column contratos.proposta.modalidade is 'Modalidade da proposta';
 comment on column contratos.proposta.nome_objeto is 'Descrição do objeto da proposta';
 comment on column contratos.proposta.numero_convenio is 'Número do convênio associado a proposta';
 comment on column contratos.proposta.ano_convenio is 'Ano do convênio associado à proposta';
 comment on column contratos.proposta.data_assinatura_convenio is 'Data de assinatura do convênio';
 comment on column contratos.proposta.codigo_programa is 'Código do programa ao qual a proposta foi submetida';
 comment on column contratos.proposta.nome_programa is 'Nome do programa ao qual a proposta foi submetida';
 comment on column contratos.proposta.identificacao_proponente is 'Proponente da proposta';
 comment on column contratos.proposta.nome_proponente is 'Nome do proponente da proposta';
 comment on column contratos.proposta.uf is 'Estado do Objeto da Proposta';
 comment on column contratos.proposta.pc_min_contrapartida is 'Percentual mínimo de contrapartida';
 comment on column contratos.proposta.nome_mandataria is 'Mandatária responsável';
 comment on column contratos.proposta.categoria is 'Categoria da proposta';
 comment on column contratos.proposta.nivel_contrato is 'Nível do contrato';
 comment on column contratos.proposta.spa_homologado is 'Status do SPA';
 comment on column contratos.proposta.apelido_empreendimento is 'Apelido do ACFFO / Empreendimento';
 comment on column contratos.proposta.versao is 'Versao usada para controlar a concorrencia';
 comment on column contratos.proposta.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.proposta.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.proposta.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.proposta.termo_compromisso_tem_mandatar is 'Indica se a modalidade tem instituicao mandatária (campo usado na modalidade termo de compromisso)';
 
 comment on column contratos.proposta_log_rec.id is 'Chave primaria do registro da tabela';
 comment on column contratos.proposta_log_rec.ano_convenio is 'Ano do convênio associado à proposta';
 comment on column contratos.proposta_log_rec.ano_proposta is 'Ano da proposta';
 comment on column contratos.proposta_log_rec.apelido_empreendimento is 'Apelido do ACFFO / Empreendimento';
 comment on column contratos.proposta_log_rec.categoria is 'Categoria da proposta';
 comment on column contratos.proposta_log_rec.codigo_programa is 'Código do programa ao qual a proposta foi submetida';
 comment on column contratos.proposta_log_rec.data_assinatura_convenio is 'Data de assinatura do convênio';
 comment on column contratos.proposta_log_rec.entity_id is 'Id da entidade que esta sendo historiada';
 comment on column contratos.proposta_log_rec.id_siconv is 'Identificador da Proposta no SICONV';
 comment on column contratos.proposta_log_rec.identificacao_proponente is 'Proponente da proposta';
 comment on column contratos.proposta_log_rec.modalidade is 'Modalidade da proposta';
 comment on column contratos.proposta_log_rec.nivel_contrato is 'Nível do contrato';
 comment on column contratos.proposta_log_rec.nome_mandataria is 'Mandatária responsável';
 comment on column contratos.proposta_log_rec.nome_objeto is 'Descrição do objeto da proposta';
 comment on column contratos.proposta_log_rec.nome_programa is 'Nome do programa ao qual a proposta foi submetida';
 comment on column contratos.proposta_log_rec.nome_proponente is 'Nome do proponente da proposta';
 comment on column contratos.proposta_log_rec.numero_convenio is 'Número do convênio associado a proposta';
 comment on column contratos.proposta_log_rec.numero_proposta is 'Número da proposta';
 comment on column contratos.proposta_log_rec.pc_min_contrapartida is 'Percentual mínimo de contrapartida';
 comment on column contratos.proposta_log_rec.spa_homologado is 'Status do SPA';
 comment on column contratos.proposta_log_rec.uf is 'Estado do Objeto da Proposta';
 comment on column contratos.proposta_log_rec.valor_contrapartida is 'Valor de contrapartida';
 comment on column contratos.proposta_log_rec.valor_global is 'Valor global aceito na análise';
 comment on column contratos.proposta_log_rec.valor_repasse is 'Valor de repasse aceito na análise';
 comment on column contratos.proposta_log_rec.versao is 'Versao usada para controlar a concorrencia';
 comment on column contratos.proposta_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.proposta_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.proposta_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.proposta_log_rec.termo_compromisso_tem_mandatar is 'Indica se a modalidade tem instituicao mandatária (campo usado na modalidade termo de compromisso)';
 

 comment on column contratos.submeta.id is 'Chave primaria do registro da tabela';
 comment on column contratos.submeta.numero is 'Numero da submeta';
 comment on column contratos.submeta.vl_repasse is 'valor do repasse';
 comment on column contratos.submeta.vl_outros is 'valor dos outros custos';
 comment on column contratos.submeta.in_regime_execucao is 'indicador do regime de execucao da fase de analise';
 comment on column contratos.submeta.vl_contrapartida is 'valor da contrapartida';
 comment on column contratos.submeta.vl_total_licitado is 'valor total licitado';
 comment on column contratos.submeta.in_situacao is 'indicador da situacao da submeta';
 comment on column contratos.submeta.descricao is 'Descricao da submeta';
 comment on column contratos.submeta.versao is 'Versao usada para controlar a concorrencia';
 comment on column contratos.submeta.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.submeta.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.submeta.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.submeta.meta_id is 'chave para tabela de Meta';
 comment on column contratos.submeta.proposta_id is 'chave para tabela de Proposta';
 comment on column contratos.submeta.lote_id is 'chave para tabela de Lote';
 comment on column contratos.submeta.id_submeta_vrpl is 'chave para submeta na fase VRPL';
 
 comment on column contratos.submeta_log_rec.id is 'Chave primaria do registro da tabela';
 comment on column contratos.submeta_log_rec.descricao is 'Descricao da submeta';
 comment on column contratos.submeta_log_rec.entity_id is 'Id da entidade que esta sendo historiada';
 comment on column contratos.submeta_log_rec.in_regime_execucao is 'indicador do regime de execucao da fase de analise';
 comment on column contratos.submeta_log_rec.in_situacao is 'indicador da situacao da submeta';
 comment on column contratos.submeta_log_rec.loteid is 'chave para tabela de Lote';
 comment on column contratos.submeta_log_rec.metaid is 'chave para tabela de Meta';
 comment on column contratos.submeta_log_rec.numero is 'Numero da submeta';
 comment on column contratos.submeta_log_rec.propostaid is 'chave para tabela de Proposta';
 comment on column contratos.submeta_log_rec.vl_contrapartida is 'valor da contrapartida';
 comment on column contratos.submeta_log_rec.vl_outros is 'valor dos outros custos';
 comment on column contratos.submeta_log_rec.vl_repasse is 'valor do repasse';
 comment on column contratos.submeta_log_rec.vl_total_licitado is 'valor total licitado';
 comment on column contratos.submeta_log_rec.versao is 'Versao usada para controlar a concorrencia';
 comment on column contratos.submeta_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.submeta_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.submeta_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.submeta_log_rec.id_submeta_vrpl is 'chave para submeta na fase VRPL';
 
 comment on column contratos.submeta_doc_complementar.data_associacao is 'TABELA AINDA NAO USADA (nao tem nem campo de auditoria)- AJUSTAR COMENTARIOS QUANDO FOR UTILIZADA';
 comment on column contratos.submeta_doc_complementar.doc_complementar_id is 'chave estrangeira para documentacao complementar';
 comment on column contratos.submeta_doc_complementar.id is 'Chave primaria do registro da tabela';
 comment on column contratos.submeta_doc_complementar.submeta_id is 'chave estrangeira para submeta';
 
 comment on column contratos.submeta_doc_complementar_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.submeta_doc_complementar_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.submeta_doc_complementar_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.submeta_doc_complementar_log_rec.data_associacao is 'TABELA AINDA NAO USADA - AJUSTAR COMENTARIOS QUANDO FOR UTILIZADA';
 comment on column contratos.submeta_doc_complementar_log_rec.doccomplementarid is 'chave estrangeira para documentacao complementar';
 comment on column contratos.submeta_doc_complementar_log_rec.entity_id is 'Id da entidade que esta sendo historiada';
 comment on column contratos.submeta_doc_complementar_log_rec.id is 'Chave primaria do registro da tabela';
 comment on column contratos.submeta_doc_complementar_log_rec.submetaid is 'chave estrangeira para submeta';
 comment on column contratos.submeta_doc_complementar_log_rec.versao is 'Versao usada para controlar a concorrencia';
 
 comment on column contratos.termo_aditivo.id is 'Chave primaria do registro da tabela';
 comment on column contratos.termo_aditivo.in_alteracao_vigencia is 'Indicador se termo aditivo eh de alteracao de vigencia';
 comment on column contratos.termo_aditivo.in_alteracao_clausula is 'Indicador se termo aditivo eh de alteracao de clausula';
 comment on column contratos.termo_aditivo.in_alteracao_objeto is 'Indicador se termo aditivo eh de alteracao de objeto';
 comment on column contratos.termo_aditivo.numero is 'Numero do termo aditivo';
 comment on column contratos.termo_aditivo.dt_assinatura is 'Data de assinatura do termo aditivo';
 comment on column contratos.termo_aditivo.dt_publicacao is 'Data de publicacao do termo aditivo';
 comment on column contratos.termo_aditivo.versao is 'Versao usada para controlar a concorrencia';
 comment on column contratos.termo_aditivo.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.termo_aditivo.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.termo_aditivo.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.termo_aditivo.contrato_id is 'Id do contrato que o termo aditivo esta vinculado';
 
 comment on column contratos.termo_aditivo_log_rec.id is 'Chave primaria do registro da tabela';
 comment on column contratos.termo_aditivo_log_rec.contratoid is 'Id do contrato que o termo aditivo esta vinculado';
 comment on column contratos.termo_aditivo_log_rec.dt_assinatura is 'Data de assinatura do termo aditivo';
 comment on column contratos.termo_aditivo_log_rec.dt_publicacao is 'Data de publicacao do termo aditivo';
 comment on column contratos.termo_aditivo_log_rec.entity_id is 'Id da entidade que esta sendo historiada';
 comment on column contratos.termo_aditivo_log_rec.in_alteracao_vigencia is 'Indicador se termo aditivo eh de alteracao de vigencia';
 comment on column contratos.termo_aditivo_log_rec.in_alteracao_clausula is 'Indicador se termo aditivo eh de alteracao de clausula';
 comment on column contratos.termo_aditivo_log_rec.in_alteracao_objeto is 'Indicador se termo aditivo eh de alteracao de objeto';
 comment on column contratos.termo_aditivo_log_rec.numero is 'Numero do termo aditivo';
 comment on column contratos.termo_aditivo_log_rec.versao is 'Versao usada para controlar a concorrencia';
 comment on column contratos.termo_aditivo_log_rec.adt_data_hora is 'Data/Hora de modificacao do registro';
 comment on column contratos.termo_aditivo_log_rec.adt_login is 'CPF do usuario que realizou a operacao';
 comment on column contratos.termo_aditivo_log_rec.adt_operacao is 'Operacao (INSERT/UPDATE/DELETE) da ultima acao no registro';
 comment on column contratos.termo_aditivo_log_rec.in_alteracao_supressao_acrescimo is 'Se diferente de nulo, existe acrescismo (ACR) ou supressao (SUP) de valor.';
 comment on column contratos.termo_aditivo_log_rec.vl_supressao_acrescimo is 'Valor do acrescimo ou da supressao, se houver.';
 comment on column contratos.termo_aditivo_log_rec.dt_nova_data_fim_vigencia is 'Nova data final de vigencia, se houver.';
 comment on column contratos.termo_aditivo_log_rec.tx_justificativa is 'Justificativa.';
 comment on column contratos.termo_aditivo_log_rec.tx_descricao_ampliacao_objeto is 'Descricao da ampliacao do objeto.';
 comment on column contratos.termo_aditivo_log_rec.in_situacao is 'Situacao do termo aditivo RAS, CON, EXC';
 
 
