version: '3.3'

services:
 db-pg:
  image: postgres:9.6
  stop_signal: SIGINT
  restart: unless-stopped
  environment:
   POSTGRES_DB: db-maisbrasil-contratos
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: db-maisbrasil-contratos
   PG_VERSION: 9.6
   PGDATA: /var/lib/postgresql/data/9.6/pgdata
  volumes:
    - $HOME/docker/volumes/postgres/9.6:/var/lib/postgresql/data/9.6/pgdata
    - ./init:/docker-entrypoint-initdb.d/
  ports:
    - 5432:5432
