ALTER SCHEMA contratos OWNER TO owner_siconv_p;

ALTER TABLE contratos.anexo_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.anexo_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.contrato_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.contrato_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.doc_complementar_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.doc_complementar_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.fornecedor_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.fornecedor_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.historico_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.historico_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.licitacao_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.licitacao_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.lote_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.lote_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.meta_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.meta_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.po_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.po_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.proposta_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.proposta_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.submeta_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.submeta_doc_complementar_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.submeta_doc_complementar_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.submeta_log_rec_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.termo_aditivo_seq OWNER TO owner_siconv_p;
ALTER TABLE contratos.termo_aditivo_log_rec_seq OWNER TO owner_siconv_p;

GRANT SELECT, USAGE  ON SEQUENCE contratos.anexo_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.anexo_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.contrato_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.contrato_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.doc_complementar_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.doc_complementar_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.fornecedor_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.fornecedor_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.historico_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.historico_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.licitacao_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.licitacao_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.lote_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.lote_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.meta_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.meta_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.po_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.po_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.proposta_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.proposta_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.submeta_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.submeta_doc_complementar_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.submeta_doc_complementar_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.submeta_log_rec_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.termo_aditivo_seq  TO owner_siconv_p;
GRANT SELECT, USAGE  ON SEQUENCE contratos.termo_aditivo_log_rec_seq  TO owner_siconv_p;

GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.anexo  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.anexo_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.contrato  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.contrato_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.doc_complementar  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.doc_complementar_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.fornecedor  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.fornecedor_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.historico  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.historico_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.licitacao  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.licitacao_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.lote  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.lote_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.meta  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.meta_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.po  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.po_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.proposta  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.proposta_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.submeta  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.submeta_doc_complementar  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.submeta_doc_complementar_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.submeta_log_rec  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.termo_aditivo  TO owner_siconv_p;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE contratos.termo_aditivo_log_rec  TO owner_siconv_p;

ALTER FUNCTION contratos.anexo_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.contrato_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.doc_complementar_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.fornecedor_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.historico_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.licitacao_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.lote_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.meta_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.po_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.proposta_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.submeta_doc_complementar_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.submeta_trigger() OWNER TO owner_siconv_p;
ALTER FUNCTION contratos.termo_aditivo_trigger() OWNER TO owner_siconv_p;


