export enum Role {
  FISCAL_CONVENENTE = 'FISCAL_CONVENENTE',
  GESTOR_CONVENIO_CONVENENTE = 'GESTOR_CONVENIO_CONVENENTE',
  GESTOR_FINANCEIRO_CONVENENTE = 'GESTOR_FINANCEIRO_CONVENENTE',
  OPERADOR_FINANCEIRO_CONVENENTE = 'OPERADOR_FINANCEIRO_CONVENENTE',
  GESTOR_CONVENIO_CONCEDENTE = 'GESTOR_CONVENIO_CONCEDENTE',
  GESTOR_CONVENIO_INSTITUICAO_MANDATARIA = 'GESTOR_CONVENIO_INSTITUICAO_MANDATARIA',
  ADMINISTRADOR_SISTEMA = 'ADMINISTRADOR_SISTEMA',
  ADMINISTRADOR_SISTEMA_ORGAO_EXTERNO = 'ADMINISTRADOR_SISTEMA_ORGAO_EXTERNO'
}
export namespace Role {
  export function valueOf(roleStr: string): Role {
    return (<any>Role)[roleStr];
  }
}
